package com.arca.equipfix.gambachanneltv.data.models;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "reminders".
*/
public class ReminderDao extends AbstractDao<Reminder, Long> {

    public static final String TABLENAME = "reminders";

    /**
     * Properties of entity Reminder.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "title");
        public final static Property ChannelId = new Property(2, int.class, "channelId", false, "channel_id");
        public final static Property ChannelName = new Property(3, String.class, "channelName", false, "channel_name");
        public final static Property StartDate = new Property(4, java.util.Date.class, "startDate", false, "start_date");
        public final static Property Unique = new Property(5, boolean.class, "unique", false, "unique");
        public final static Property Played = new Property(6, boolean.class, "played", false, "played");
    }


    public ReminderDao(DaoConfig config) {
        super(config);
    }
    
    public ReminderDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"reminders\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"title\" TEXT," + // 1: title
                "\"channel_id\" INTEGER NOT NULL ," + // 2: channelId
                "\"channel_name\" TEXT," + // 3: channelName
                "\"start_date\" INTEGER," + // 4: startDate
                "\"unique\" INTEGER NOT NULL ," + // 5: unique
                "\"played\" INTEGER NOT NULL );"); // 6: played
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"reminders\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Reminder entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
        stmt.bindLong(3, entity.getChannelId());
 
        String channelName = entity.getChannelName();
        if (channelName != null) {
            stmt.bindString(4, channelName);
        }
 
        java.util.Date startDate = entity.getStartDate();
        if (startDate != null) {
            stmt.bindLong(5, startDate.getTime());
        }
        stmt.bindLong(6, entity.getUnique() ? 1L: 0L);
        stmt.bindLong(7, entity.getPlayed() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Reminder entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
        stmt.bindLong(3, entity.getChannelId());
 
        String channelName = entity.getChannelName();
        if (channelName != null) {
            stmt.bindString(4, channelName);
        }
 
        java.util.Date startDate = entity.getStartDate();
        if (startDate != null) {
            stmt.bindLong(5, startDate.getTime());
        }
        stmt.bindLong(6, entity.getUnique() ? 1L: 0L);
        stmt.bindLong(7, entity.getPlayed() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Reminder readEntity(Cursor cursor, int offset) {
        Reminder entity = new Reminder( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.getInt(offset + 2), // channelId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // channelName
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // startDate
            cursor.getShort(offset + 5) != 0, // unique
            cursor.getShort(offset + 6) != 0 // played
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Reminder entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setChannelId(cursor.getInt(offset + 2));
        entity.setChannelName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStartDate(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setUnique(cursor.getShort(offset + 5) != 0);
        entity.setPlayed(cursor.getShort(offset + 6) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Reminder entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Reminder entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Reminder entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
